// Original lines written for Discipline Log. Rotates by day-of-year, no network needed.
const QUOTES = [
  "Discipline is just a decision you don't have to make twice.",
  "Small marks on a grid, every day, build something you can't fake.",
  "You don't rise to your goals. You fall to your systems.",
  "The streak isn't the point. What the streak built you into is.",
  "Consistency is a quiet kind of proof.",
  "Nobody sees day 4. Everyone sees day 400.",
  "Motivation starts it. Structure finishes it.",
  "A habit skipped once is a decision. Skipped twice, it's a pattern.",
  "Log it even on the day you don't feel like it. Especially then.",
  "You're not behind. You're mid-build.",
  "The work compounds quietly, then all at once.",
  "Show up smaller than you'd like, but show up.",
  "Discipline is choosing between what you want now and what you want most.",
  "Every checked box is a vote for who you're becoming.",
  "Progress is boring in real time and obvious in hindsight.",
  "The bar isn't perfect. The bar is present.",
  "Some days the habit is the whole win.",
  "You don't need more willpower. You need a better system.",
  "Track it, don't judge it. The number will speak for itself.",
  "Discomfort now is just tuition for who you'll be later.",
  "The record doesn't lie, and neither does the gap in it.",
  "Do the rep. The reps are the whole program.",
  "You're building a track record, one square at a time.",
  "The grid remembers what excuses forget.",
  "A short streak beaten twice becomes a long one.",
  "Effort compounds. So does neglect.",
  "The habit is the point, not the mood you're in about it.",
  "You don't need a perfect week. You need a non-zero day.",
  "Consistency turns identity into evidence.",
  "The plan survives contact with a bad day only if you log it anyway.",
  "Discipline is remembering what you actually want.",
  "The version of you that quits today still has to live with tomorrow's version.",
  "One entry doesn't matter. Zero entries never lie.",
  "Standards are just habits you refuse to skip.",
  "You're not chasing motivation. You're outlasting it.",
  "The chart doesn't care how you felt. It cares what you did.",
  "Discipline is freedom wearing a work shirt.",
  "Every day logged is a brick. Every day skipped is a gap in the wall.",
  "The hard part was never the habit. It was the decision to start again.",
  "Build the floor so low you can't help but clear it.",
  "You don't have to want to. You just have to do it anyway.",
  "The best time to fix a broken streak is right now, not tomorrow.",
  "Discipline doesn't ask for inspiration. It asks for a checkbox.",
  "What you repeat, you become.",
  "A habit is a promise you keep to no one but yourself.",
  "The log is boring because the work is boring. That's the whole trick.",
  "Nobody drowns from one bad day. They drown from the pattern after it.",
  "You're not behind schedule. There is no schedule but the one you keep.",
  "The mark on the grid is small. The message to yourself isn't.",
  "Discipline is the bridge between goals and results.",
  "Today's entry is tomorrow's evidence.",
  "You win the day by refusing to lose the habit.",
  "It's never too late to start the streak that matters.",
  "The system doesn't need you to feel ready. It needs you to show up.",
  "Every square filled in is an argument against giving up.",
  "Consistency isn't glamorous. That's exactly why it works.",
  "Do it today so future-you doesn't have to catch up.",
  "The habit doesn't care about your excuse. Log it anyway.",
  "Small, repeated, unglamorous — that's the whole formula.",
  "You're not too busy. You're just not tracking it yet."
];
